### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by marcosscriven** [amosstorkey/virgintivocec#1]
Hi - sorry if I'm being dim, but I see your readme, but no actual code. Checked if you had any branches but can't see anything other than master.

Looks like a really neat idea!

**Comment by amosstorkey** [comment]
The code is now up - it was delayed as osmc changed how it was handling libcec, but was broken. It was unclear what route they were going to take for future libcec (in the end they have separated concerns from their own code for kodi, and the vanilla libcec library).

**Comment by marcosscriven** [comment]
Thanks!
